Repository espressif/vscode-esp-idf-extension, pull requests merged in 2020-10, with the labels that each got.

#195 Add new project compiler path
  src/config.ts
  src/examples/ExamplesPanel.ts
  src/extension.ts
  templates/.vscode/c_cpp_properties.json
  templates/.vscode/settings.json
Labels: enhancement

#192 Update GUI Menuconfig Title
  README.md
  i18n/en/out/espIdf/menuconfig/MenuconfigPanel.i18n.json
  i18n/en/package.i18n.json
  i18n/es/out/espIdf/menuconfig/MenuconfigPanel.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/out/espIdf/menuconfig/MenuconfigPanel.i18n.json
  i18n/zh-CN/package.i18n.json
  package.nls.json
  src/espIdf/menuconfig/MenuconfigPanel.ts
Labels: Project Enhancement

#186 Update docs
  README.md
Labels: Project Enhancement, docs-missing

#198 Enhance icons usages
  media/dark/add.svg
  media/dark/edit.svg
  media/dark/refresh.svg
  media/dark/sign-in.svg
  media/dark/sign-out.svg
  media/dark/trash.svg
  media/light/add.svg
  media/light/edit.svg
  media/light/refresh.svg
  media/light/sign-in.svg
  media/light/sign-out.svg
  media/light/trash.svg
  package.json
  src/coverage/coverageService.ts
  src/espIdf/menuconfig/MenuconfigPanel.ts
  src/espIdf/size/idfSizePanel.ts
  src/espIdf/tracing/appTracePanel.ts
  src/espIdf/tracing/system-view/panel.ts
  src/examples/ExamplesPanel.ts
  src/onboarding/OnboardingPanel.ts
  src/utils.ts
Labels: Project Enhancement, enhancement

#180 Add Changelog Viewer
  CHANGELOG.md
  src/changelog-viewer.ts
  src/config.ts
  src/extension.ts
  src/utils.ts
Labels: Feature

#202 Fix dispose sdkconfig editor on confserver exit error
  src/espIdf/menuconfig/confServerProcess.ts
Labels: bugfix

#200 Codicons in sdkconfig editor (VSC-467)
  package.json
  src/espIdf/menuconfig/MenuconfigPanel.ts
  src/views/menuconfig/components/SideNavItem.vue
  src/views/menuconfig/components/configElement.vue
  src/views/menuconfig/main.ts
  yarn.lock
Labels: enhancement

#176 Core Dump + GDB Stub (VSC-445)
  .github/workflows/ci.yml
  docs/POSTMORTEM.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  requirements.txt
  schema.i18n.json
  src/espIdf/core-dump/esp-core-dump-py-tool.ts
  src/espIdf/core-dump/index.ts
  src/espIdf/debugAdapter/debugAdapterManager.ts
  src/espIdf/monitor/index.ts
  src/extension.ts
  src/flash/flashTask.ts
  src/pythonManager.ts
Labels: Feature

#205 mv to vscode codicons
  package.json
  src/views/commons/espCommons.scss
  src/views/onboarding/App.vue
  src/views/onboarding/Download.vue
  src/views/onboarding/components/IDFManual.vue
  src/views/onboarding/components/ToolCheck.vue
  src/views/onboarding/components/ToolsDownloadStep.vue
  src/views/onboarding/main.ts
  src/views/size/index.html
  src/views/tracing/components/CallStack.vue
  src/views/tracing/components/LeakList.vue
  src/views/tracing/index.html
  webpack.config.js
  yarn.lock
Labels: enhancement
