Repository espressif/vscode-esp-idf-extension, pull requests merged in 2020-04, with the labels that each got.

#62 Support for ESP-IDF Integrated terminal (VSC-266)
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  snippets/kconfig.code-snippets
  src/extension.ts
  src/utils.ts
  yarn.lock
Labels: enhancement

#82 IDF Monitor Terminal Issue (VSC-285)
  src/extension.ts
Labels: bugfix

#85 VSCode Marketplace Search Optimization (VSC-307)
  package.json
Labels: Project Enhancement

#80 Fix space in path in python issues (VSC-283)
  src/build/build.ts
  src/espIdf/apptrace/tools/logTraceProc.ts
  src/espIdf/debugAdapter/debugAdapterManager.ts
  src/espIdf/menuconfig/confServerProcess.ts
  src/espIdf/openOcd/openOcdManager.ts
  src/extension.ts
  src/flash/flash.ts
  src/onboarding/OnboardingPanel.ts
  src/onboarding/pythonReqsManager.ts
  src/onboarding/toolsInstall.ts
  src/pythonManager.ts
  src/utils.ts
  src/views/onboarding/store/actions.ts
Labels: bugfix

#73 Enhance project structure (VSC-277)
  .bandit
  .flake8
  .github/workflows/ci.yml
  .huskyrc.json
  .vscodeignore
  README.md
  media/espressif_icon.png
  package.json
Labels: Project Enhancement

#68 find xtensa toolchain full path fix getProjectName (VSC-272)
  docs/DEBUGGING.md
  src/extension.ts
  src/utils.ts
Labels: bugfix
