Repository espressif/vscode-esp-idf-extension, pull requests merged in 2020-02, with the labels that each got.

#30 Enhance Build Output (VSC-235)
  src/build/build.ts
  yarn.lock
Labels: bugfix, enhancement

#36 Use new IDFv4 Cmake `idf_component_register` API (VSC-240)
  templates/template-app/.gitignore
  templates/template-app/main/CMakeLists.txt
Labels: enhancement

#35 Fix the command typo bug (VSC-241)
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.nls.json
Labels: bugfix

#38 Fix the idf_component_register calling params (VSC-243)
  templates/template-app/.gitignore
  templates/template-app/main/CMakeLists.txt
Labels: bugfix

#40 remove site packages (VSC-245)
  src/pythonManager.ts
  templates/.vscode/c_cpp_properties.json
Labels: bugfix

#47 fix uppercase search (VSC-252)
  src/views/menuconfig/Menuconfig.vue
Labels: bugfix

#41 Feature/localization kv val (VSC-226) (VSC-246)
  gulpfile.js
  i18n/en/out/espIdf/menuconfig/MenuconfigPanel.i18n.json
  i18n/es/out/extension.i18n.json
  i18n/zh-CN/out/extension.i18n.json
  package.json
  schema.i18n.json
  src/localizationDictionary.ts
  yarn.lock
Labels: enhancement

#48 rm unused i18n field, add unknown field (VSC-253)
  gulpfile.js
  schema.i18n.json
Labels: bugfix
