Repository espressif/vscode-esp-idf-extension, pull requests merged in 2020-09, with the labels that each got.

#166 Bugfix for webview background color issue
  src/views/commons/espCommons.scss
Labels: bugfix

#174 [Bug Fix]: Device Baud Rate not Setting Issue (VSC-442)
  src/extension.ts
  src/idfConfiguration.ts
Labels: bugfix, esp32-forum

#139 add arguments to debug adapter manager (VSC-379)
  .github/workflows/ci.yml
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  requirements.txt
  schema.i18n.json
  src/espIdf/debugAdapter/debugAdapterManager.ts
  src/extension.ts
  src/flash/flashTask.ts
  src/pythonManager.ts
Labels: enhancement
