Repository espressif/vscode-esp-idf-extension, pull requests merged in 2020-08, with the labels that each got.

#140 Initial ESP-ADF and ESP-MDF support (VSC-380)
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/common/abstractCloning.ts
  src/espAdf/espAdfDownload.ts
  src/espMdf/espMdfDownload.ts
  src/examples/ExamplesPanel.ts
  src/extension.ts
  src/utils.ts
  src/views/examples/Examples.vue
  yarn.lock
Labels: Feature

#155 Add interface cfg-file into the default `idf.openOcdConfigs`config (VSC-420)
  package.json
Labels: bugfix

#156 Update prerequisite from Readme (VSC-423)
  README.md
Labels: Project Enhancement
