Repository espressif/vscode-esp-idf-extension, pull requests merged in 2020-12, with the labels that each got.

#220 Notifications silent mode
  README.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/build/buildTask.ts
  src/flash/flashTask.ts
  src/taskManager.ts
  src/userNotificationManager/userNotificationManager.ts
Labels: enhancement

#215 Enhance Search in docs using Tree View and showing all the references (VSC-483)
  .gitignore
  .vscodeignore
  README.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/config.ts
  src/espIdf/documentation/docResultsTreeView.ts
  src/espIdf/documentation/getDocsVersion.ts
  src/espIdf/documentation/getSearchResults.ts
  src/extension.ts
  src/utils.ts
  yarn.lock
Labels: enhancement

#235 Show Rainmaker LoggedIn User's Info (VSC-498)
  src/extension.ts
  src/rainmaker/client/index.ts
  src/rainmaker/client/model.ts
  src/rainmaker/view/index.ts
  src/rainmaker/view/item_generator.ts
Labels: enhancement

#233 update yarn lock gulp-cli and vscode api
  package.json
  src/extension.ts
  src/rainmaker/view/item.ts
  yarn.lock
Labels: bugfix

#240 Remove trailing comma in settings.json template file (VSC-504)
  templates/.vscode/settings.json
Labels: bugfix

#229 Many small bugfixes
  README.md
  docs/ONBOARDING.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  idf_versions.txt
  package.nls.json
  src/common/abstractCloning.ts
  src/espIdf/arduino/addArduinoComponent.ts
  src/espIdf/menuconfig/confServerProcess.ts
  src/examples/ExamplesPanel.ts
  src/extension.ts
  src/installManager.ts
  src/onboarding/espIdfDownload.ts
  src/pythonManager.ts
  src/rainmaker/view/item.ts
  src/rainmaker/view/item_generator.ts
  src/taskManager.ts
  src/utils.ts
  src/views/examples/Examples.vue
Labels: bugfix

#224 Add WSL serial support
  docs/WSL.md
  src/espIdf/serial/serialPort.ts
  src/extension.ts
  src/flash/flashTask.ts
  wsl_get_serial_list.ps
Labels: enhancement

#183 JTAG Flash Support (VSC-487)
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/espIdf/openOcd/openOcdManager.ts
  src/espIdf/openOcd/tcl/tclClient.ts
  src/extension.ts
  src/flash/jtag.ts
  src/utils.ts
Labels: Feature, Release: Awaited for Dependencies, ongoing

#151 Add eFuse Explorer (read-only) (VSC-412)
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/efuse/index.ts
  src/efuse/view/index.ts
  src/efuse/view/item.ts
  src/efuse/view/item_generator.ts
  src/extension.ts
  src/rainmaker/view/index.ts
Labels: Feature, Release: Awaited for Dependencies, ongoing

#250 Full clean button and command
  README.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  src/extension.ts
Labels: Feature

#246 NVS Partition editor
  README.md
  docs/NVS_PARTITION_EDITOR.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  src/espIdf/nvs/partitionTable/panel.ts
  src/extension.ts
  src/views/commons/espCommons.scss
  src/views/nvs-partition-table/App.vue
  src/views/nvs-partition-table/components/Header.vue
  src/views/nvs-partition-table/components/PartitionTable.vue
  src/views/nvs-partition-table/components/Row.vue
  src/views/nvs-partition-table/main.ts
  src/views/nvs-partition-table/store/index.ts
  src/views/nvs-partition-table/util.ts
  webpack.config.js
  yarn.lock
Labels: Feature

#170 Partition Table Editor UI (VSC-439)
  docs/PARTITION_TABLE_EDITOR.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  media/screenshots/partition_table_editor.png
  package.json
  package.nls.json
  schema.i18n.json
  src/config.ts
  src/espIdf/partition-table/index.ts
  src/extension.ts
  src/views/partition-table/App.vue
  src/views/partition-table/components/Header.vue
  src/views/partition-table/components/PartitionTable.vue
  src/views/partition-table/components/Row.vue
  src/views/partition-table/main.ts
  src/views/partition-table/store/index.ts
  src/views/partition-table/util.ts
  webpack.config.js
Labels: Feature
