Repository espressif/vscode-esp-idf-extension, pull requests merged in 2020-06, with the labels that each got.

#90 Code coverage (VSC-312)
  README.md
  docs/COVERAGE.md
  esp_debug_adapter/requirements.txt
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/coverage/coverageService.ts
  src/coverage/renderer.ts
  src/extension.ts
  yarn.lock
Labels: Feature

#115 :pencil2: Fix documentation typo (VSC-353)
  docs/ONBOARDING.md
Labels: Project Enhancement, docs-missing

#97 Rainmaker Support (VSC-321)
  README.md
  docs/ESP_RAINMAKER.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  media/dark/add.svg
  media/dark/edit.svg
  media/dark/refresh.svg
  media/dark/sign-in.svg
  media/dark/sign-out.svg
  media/dark/trash.svg
  media/light/add.svg
  media/light/edit.svg
  media/light/refresh.svg
  media/light/sign-in.svg
  media/light/sign-out.svg
  media/light/trash.svg
  media/log_dark.svg
  media/log_light.svg
  media/play_dark.svg
  media/play_light.svg
  media/refresh_dark.svg
  media/refresh_light.svg
  media/stop_dark.svg
  media/stop_light.svg
  package.json
  package.nls.json
  schema.i18n.json
  src/config.ts
  src/extension.ts
  src/rainmaker/client/index.ts
  src/rainmaker/client/model.ts
  src/rainmaker/index.ts
  src/rainmaker/oauth/index.ts
  src/rainmaker/store/index.ts
  src/rainmaker/view/index.ts
  src/rainmaker/view/item.ts
  src/rainmaker/view/item_generator.ts
  src/rainmaker/view/login.ts
  yarn.lock
Labels: Feature

#92 Enhance/task provider (VSC-315)
  package.json
  src/build/build.ts
  src/build/buildTask.ts
  src/extension.ts
  src/flash/flash.ts
  src/flash/flashTask.ts
  src/taskManager.ts
Labels: bugfix, enhancement

#111 Add Telemetry Support (VSC-336)
  .vscode/launch.json
  docs/TELEMETRY.md
  package.json
  src/extension.ts
  src/logger/logger.ts
  src/telemetry/index.ts
  yarn.lock
Labels: Feature

#121 Bugfix/idf tools not available (VSC-360)
  src/extension.ts
  src/idfToolsManager.ts
  src/onboarding/toolsInstall.ts
Labels: bugfix

#124 Fix the wrong Icon (VSC-363)
  src/espIdf/tracing/tree/appTraceTreeDataProvider.ts
Labels: bugfix

#123 validate workspace folders length (VSC-362)
  src/espIdf/debugAdapter/debugAdapterManager.ts
  src/espIdf/openOcd/openOcdManager.ts
  src/espIdf/tracing/appTraceManager.ts
  src/espIdf/tracing/appTracePanel.ts
  src/espIdf/tracing/heapTraceManager.ts
  src/espIdf/tracing/tree/appTraceArchiveTreeDataProvider.ts
  src/extension.ts
  src/idfConfiguration.ts
  src/onboarding/OnboardingPanel.ts
Labels: bugfix

#129 Fix the IDF Size UI Bar Size Issue (VSC-368)
  src/views/commons/espCommons.scss
  src/views/size/index.html
Labels: bugfix

#113 :bug: Fix python venv install wheel issue in Linux (VSC-348)
  src/idfConfiguration.ts
  src/onboarding/OnboardingPanel.ts
  src/pythonManager.ts
  src/utils.ts
  src/views/onboarding/GitPyCheck.vue
  src/views/onboarding/main.ts
  src/views/onboarding/store/mutations.ts
  src/views/onboarding/store/onboarding.ts
  src/views/onboarding/store/types.ts
Labels: bugfix, os:linux

#134 fix args for debug adapter update doc (VSC-373)
  docs/DEBUGGING.md
  package.json
  src/espIdf/debugAdapter/debugAdapterManager.ts
  src/extension.ts
  src/onboarding/OnboardingPanel.ts
  src/rainmaker/view/index.ts
  templates/.vscode/launch.json
  yarn.lock
Labels: bugfix

#117 Arduino as an ESP32 component (VSC-354)
  README.md
  i18n/en/out/extension.i18n.json
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  src/espIdf/arduino/addArduinoComponent.ts
  src/examples/ExamplesPanel.ts
  src/extension.ts
  src/utils.ts
  templates/arduino-as-component/.gitignore
  templates/arduino-as-component/CMakeLists.txt
  templates/arduino-as-component/main/CMakeLists.txt
  templates/arduino-as-component/main/main.cpp
  templates/fibonacci-app/.gitignore
Labels: Feature

#135 add idf task definition (VSC-374)
  package.json
  src/build/buildTask.ts
  src/flash/flashTask.ts
  src/taskManager.ts
Labels: enhancement

#120 System View Tracing (VSC-357)
  README.md
  docs/SYS_VIEW_TRACING_VIEWER.md
  package.json
  src/espIdf/tracing/system-view/index.ts
  src/espIdf/tracing/system-view/model.ts
  src/espIdf/tracing/system-view/panel.ts
  src/espIdf/tracing/system-view/parser.ts
  src/espIdf/tracing/tree/appTraceArchiveTreeDataProvider.ts
  src/extension.ts
  src/views/system-view/App.vue
  src/views/system-view/components/Loading.vue
  src/views/system-view/components/Plot.vue
  src/views/system-view/components/Settings.vue
  src/views/system-view/components/Table.vue
  src/views/system-view/main.ts
  src/views/system-view/plot.ts
  src/views/system-view/stats.ts
  src/views/system-view/store/index.ts
  src/views/system-view/store/plotLayout.ts
  src/views/system-view/table.ts
  src/views/system-view/util.ts
  webpack.config.js
  yarn.lock
Labels: Feature, enhancement
