Repository espressif/vscode-esp-idf-extension, pull requests merged in 2020-05, with the labels that each got.

#98 Remove audit step from CI (VSC-322)
  .github/workflows/ci.yml
  .github/workflows/yarn_audit.yml
Labels: Project Enhancement

#103 templates: typos and wdg timeout bypass for the Fibonacci template (VSC-327)
  templates/fibonacci-app/main/main.c
Labels: bugfix

#102 Use webview.asWebviewUri API (VSC-326)
  src/espIdf/menuconfig/MenuconfigPanel.ts
  src/espIdf/size/idfSizePanel.ts
  src/espIdf/tracing/appTracePanel.ts
  src/examples/ExamplesPanel.ts
  src/examples/createExamplesHtml.ts
  src/onboarding/OnboardingPanel.ts
  src/onboarding/createOnboardingHtml.ts
Labels: API Upgrade, Project Enhancement, enhancement

#107 add powershell env var terminal (VSC-332)
  src/extension.ts
Labels: bugfix, os:windows-only

#108 add regex to include config on search string (VSC-333)
  src/views/menuconfig/Menuconfig.vue
Labels: enhancement

#109 :bug: Fix the target name (VSC-334)
  src/extension.ts
Labels: bugfix

#112 Add Heap Tracing Docs for release (VSC-339)
  README.md
  docs/HEAP_TRACING.md
  src/espIdf/tracing/tree/appTraceArchiveTreeDataProvider.ts
  src/espIdf/tracing/tree/appTraceTreeDataProvider.ts
Labels: Project Enhancement
