Repository espressif/vscode-esp-idf-extension, pull requests merged in 2021-01, with the labels that each got.

#263 Update Changelog File
  CHANGELOG.md
Labels: Project Enhancement

#274 Fix monitor init cmd
  src/extension.ts
  src/utils.ts
Labels: bugfix

#268 Bugfix Icon Issue with command
  package.json
Labels: bugfix

#267 Fix Typo for Changelog Viewer
  src/changelog-viewer.ts
Labels: bugfix

#281 rm check tools before cmds update tasks
  src/build/buildTask.ts
  src/extension.ts
  templates/.vscode/tasks.json
Labels: bugfix

#286 Select openOCD board command
  README.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/espIdf/openOcd/boardConfiguration.ts
  src/espIdf/openOcd/openOcdManager.ts
  src/espIdf/tracing/appTraceManager.ts
  src/espIdf/tracing/heapTraceManager.ts
  src/extension.ts
Labels: Feature

#296 Fix recent change to OpenOCD config files
  src/espIdf/openOcd/boardConfiguration.ts
  src/espIdf/tracing/appTraceManager.ts
  src/extension.ts
Labels: bugfix

#284 Enhance/readme
  README.md
  docs/COVERAGE.md
  docs/C_CPP_CONFIGURATION.md
  docs/DEBUGGING.md
  docs/FEATURES.md
  docs/HARDWARE_SUPPORT.md
  docs/INSTALL.md
  docs/LANG_CONTRIBUTE.md
  docs/MULTI_PROJECTS.md
  docs/POSTMORTEM.md
  docs/SETTINGS.md
  docs/SETUP.md
  docs/WSL.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  media/onboarding.png
  package.nls.json
Labels: Project Enhancement, enhancement

#216 Added Russian localization (VSC-491)
  i18n/en/out/espIdf/menuconfig/MenuconfigPanel.i18n.json
  i18n/es/out/espIdf/menuconfig/MenuconfigPanel.i18n.json
  i18n/ru/out/espIdf/menuconfig/MenuconfigPanel.i18n.json
  i18n/ru/out/espIdf/serial/SerialPort.i18n.json
  i18n/ru/out/espIdf/size/idfSize.i18n.json
  i18n/ru/out/extension.i18n.json
  i18n/ru/out/idfComponentsDataProvider.i18n.json
  i18n/ru/out/idfConfiguration.i18n.json
  i18n/ru/out/utils.i18n.json
  i18n/ru/package.i18n.json
  i18n/ru/views/menuconfig.i18n.json
  i18n/zh-CN/out/espIdf/menuconfig/MenuconfigPanel.i18n.json
  schema.i18n.json
Labels: enhancement

#291 fix terminal output close bugs
  src/build/buildTask.ts
  src/espIdfCustomTerminal.ts
Labels: bugfix

#300 Update Translations
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.nls.json
Labels: Project Enhancement, enhancement

#255 Feature/doctor cmd
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  .vscodeignore
  README.md
  gulpfile.js
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/ru/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/extension.ts
  src/support/checkEspIdfRequirements.ts
  src/support/checkEspIdfTools.ts
  src/support/checkExtensionRequirements.ts
  src/support/checkSystemInfo.ts
  src/support/checkVscodeFiles.ts
  src/support/configurationAccess.ts
  src/support/configurationSettings.ts
  src/support/espIdfVersion.ts
  src/support/execChildProcess.ts
  src/support/gitVersion.ts
  src/support/index.ts
  src/support/initReportObj.ts
  src/support/pipVersion.ts
  src/support/pythonPackages.ts
  src/support/pythonVersion.ts
  src/support/types.ts
  src/support/writeReport.ts
Labels: Feature

#302 Add Report button where user can report
  src/userNotificationManager/userNotificationManager.ts
Labels: Project Enhancement, enhancement

#301 Fix JTAG Flashing issue (on windows)
  docs/SETTINGS.md
  package.json
  src/extension.ts
  src/flash/jtag.ts
Labels: bugfix, os:windows
