Repository espressif/vscode-esp-idf-extension, pull requests merged in 2021-02, with the labels that each got.

#308 CI Enhancements
  .github/workflows/release.yml
  package.json
Labels: Project Enhancement

#304 fix class menuconfig select
  src/views/menuconfig/components/configElement.vue
Labels: bugfix

#311 ignore patch version in python_env directory making
  src/idfToolsManager.ts
  src/pythonManager.ts
Labels: bugfix

#312 update arduino esp32 branches
  README.md
  docs/FEATURES.md
  src/config.ts
  src/espIdf/arduino/addArduinoComponent.ts
Labels: bugfix

#315 add ninja build summary from chromium tools
  README.md
  external/chromium/LICENSE
  external/chromium/ninja-build-summary.py
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/ru/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/extension.ts
Labels: Feature / Enhancement Request

#320 add espAdfPath espMdfPath to platform dep settings
  src/idfConfiguration.ts
Labels: bugfix

#319 Relocate CMakeLists Schema to root directory
  cmakeListsSchema.json
  gulpfile.js
  package.json
  src/cmake/cmakeListsBuilder.ts
Labels: bugfix

#325 dispose confserver command
  README.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/ru/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  src/extension.ts
Labels: Feature
