Repository espressif/vscode-esp-idf-extension, pull requests merged in 2021-06, with the labels that each got.

#431 Fix app tracing trace file path
  docs/tutorial/install.md
  media/tutorials/setup/advanced-manual.png
  src/espIdf/tracing/appTraceManager.ts
Labels: stale

#444 fix idf git python setup
  docs/tutorial/install.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/ru/package.i18n.json
  i18n/zh-CN/package.i18n.json
  media/tutorials/setup/select-esp-idf.png
  package.json
  package.nls.json
  schema.i18n.json
  src/checkExtensionSettings.ts
  src/config.ts
  src/coverage/configureProject.ts
  src/espIdf/arduino/addArduinoComponent.ts
  src/espIdf/documentation/getSearchResults.ts
  src/extension.ts
  src/idfToolsManager.ts
  src/pythonManager.ts
  src/setup/SetupPanel.ts
  src/setup/embedGitPy.ts
  src/setup/espIdfDownloadStep.ts
  src/setup/espIdfJson.ts
  src/setup/installPyReqs.ts
  src/setup/pyReqsInstallStep.ts
  src/setup/setupInit.ts
  src/setup/toolsDownloadStep.ts
  src/utils.ts
  src/views/setup/Install.vue
  src/views/setup/ToolsCustom.vue
  src/views/setup/components/selectEspIdf.vue
Labels: bugfix

#443 update srcs in CMakelists file enable disable
  docs/SETTINGS.md
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/ru/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/cmake/srcsWatcher.ts
Labels: Feature

#273 Add component manager UI Render (VSC-696)
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/ru/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/component-manager/panel.ts
  src/component-manager/utils.ts
  src/config.ts
  src/extension.ts
Labels: Feature
