Repository espressif/vscode-esp-idf-extension, pull requests merged in 2022-01, with the labels that each got.

#566 WIP: VSC-294 DFU support
  i18n/en/package.i18n.json
  i18n/es/package.i18n.json
  i18n/ru/package.i18n.json
  i18n/zh-CN/package.i18n.json
  package.json
  package.nls.json
  schema.i18n.json
  src/build/buildCmd.ts
  src/build/buildTask.ts
  src/extension.ts
  src/flash/dfu.ts
  src/flash/flashCmd.ts
  src/flash/flashTask.ts
  src/flash/uartFlash.ts
  src/test/suite/dfu.test.ts
  testFiles/dfu-list.txt
Labels: ongoing

#620 check core requirements first
  src/setup/setupInit.ts
Labels: bugfix

#619 update compiler path when IDF_TARGET changes
  src/extension.ts
  src/utils.ts
Labels: enhancement

#621 add tutorial links
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  docs/C_CPP_CONFIGURATION.md
  docs/DEBUGGING.md
  docs/INSTALL.md
  docs/SETUP.md
  docs/tutorial/debugging.md
  docs/tutorial/install.md
Labels: enhancement

#622 clean dirty repositories
  .github/workflows/ci.yml
  src/setup/espIdfDownload.ts
  src/utils.ts
Labels: bugfix, area:onboarding
