Repository espressif/vscode-esp-idf-extension, pull requests merged in 2022-08, with the labels that each got.

#766 fix core requirements path for doctor cmd
  src/setup/setupInit.ts
  src/support/checkEspIdfRequirements.ts
  templates/.devcontainer/Dockerfile
  templates/.devcontainer/devcontainer.json
Labels: bugfix

#771 add existing project tutorial
  docs/ONBOARDING.md
  docs/tutorial/existing_idf_project.md
  docs/tutorial/toc.md
  templates/.devcontainer/Dockerfile
Labels: docs-missing

#767 add preview targets set-target support
  package.json
  src/coverage/coverageService.ts
  src/espIdf/debugAdapter/debugAdapterManager.ts
  src/espIdf/openOcd/boardConfiguration.ts
  src/espIdf/setTarget/getTargets.ts
  src/espIdf/setTarget/index.ts
  src/espIdf/setTarget/setTargetInIdf.ts
  src/espIdf/tracing/gdbHeapTraceManager.ts
  src/espIdf/tracing/tools/xtensa/abstractXtensaTools.ts
  src/extension.ts
  src/utils.ts
Labels: enhancement

#774 Add extra button for flashing
  docs/tutorial/partition_editor.md
  media/tutorials/partition_table/partition_editor.png
  src/views/partition-table/components/Header.vue
  src/views/partition-table/main.ts
Labels: bugfix
