Repository espressif/vscode-esp-idf-extension, pull requests merged in 2024-11, with the labels that each got.

#1332 [VSC-1514] add idf path idf tools path to created example
  l10n/bundle.l10n.es.json
  l10n/bundle.l10n.pt.json
  l10n/bundle.l10n.ru.json
  l10n/bundle.l10n.zh-CN.json
  src/examples/ExamplesPanel.ts
  src/extension.ts
  src/newProject/newProjectInit.ts
  src/newProject/newProjectPanel.ts
  src/newProject/utils.ts
  src/test/project.test.ts
  src/utils.ts
Labels: bugfix

#1338 [VSC-1515] fix unit tests not being refresh
  src/espIdf/unitTest/adapter.ts
Labels: bugfix

#1342 [VSC-1510] rm old docs update links
  .github/ISSUE_TEMPLATE/Issue-report.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_production.yml
  README.md
  docs/COVERAGE.md
  docs/C_CPP_CONFIGURATION.md
  docs/DEBUGGING.md
  docs/ESP_RAINMAKER.md
  docs/EXTENSION_TESTS.md
  docs/FEATURES.md
  docs/HARDWARE_SUPPORT.md
  docs/HEAP_TRACING.md
  docs/INSTALL.md
  docs/MANUAL_TESTING.md
  docs/MULTI_PROJECTS.md
  docs/NVS_PARTITION_EDITOR.md
  docs/ONBOARDING.md
  docs/PARTITION_TABLE_EDITOR.md
  docs/POSTMORTEM.md
  docs/PROJECT_CONFIGURATION.md
  docs/QEMU.md
  docs/SETTINGS.md
  docs/SETUP.md
  docs/SYS_VIEW_TRACING_VIEWER.md
  docs/UNIT_TESTING.md
  docs/WSL.md
  docs/tutorial/additional_frameworks.md
  docs/tutorial/app_tracing.md
  docs/tutorial/basic_use.md
  docs/tutorial/cmakelists_editor.md
  docs/tutorial/code_coverage.md
  docs/tutorial/debugging.md
  docs/tutorial/dfu.md
  docs/tutorial/efuse.md
  docs/tutorial/existing_idf_project.md
  docs/tutorial/heap_tracing.md
  docs/tutorial/hints_viewer.md
  docs/tutorial/install.md
  docs/tutorial/multiple_config.md
  docs/tutorial/new_project_wizard.md
  docs/tutorial/nvs_partition_editor.md
  docs/tutorial/partition_editor.md
  docs/tutorial/project_configuration.md
  docs/tutorial/rainmaker.md
  docs/tutorial/toc.md
  docs/tutorial/using-docker-container.md
  docs/tutorial/wsl.md
  docs_espressif/zh_CN/conf.py
  docs_espressif/zh_CN/index.rst
  src/coverage/coverageService.ts
  src/extension.ts
  src/views/setup/Welcome.vue
  src/views/welcome/App.vue
Labels: documentation 📝

#1271 [VSC-1409] Add check for missing compile_commands.json in IDF projects
  l10n/bundle.l10n.es.json
  l10n/bundle.l10n.pt.json
  l10n/bundle.l10n.ru.json
  l10n/bundle.l10n.zh-CN.json
  package.json
  src/build/buildTask.ts
  src/espIdf/reconfigure/task.ts
  src/extension.ts
  src/logger/utils.ts
Labels: ongoing

#1247 [VSC-1213] Enhance flash encryption
  docs_espressif/en/additionalfeatures.rst
  docs_espressif/en/additionalfeatures/flash-encryption.rst
  l10n/bundle.l10n.es.json
  l10n/bundle.l10n.pt.json
  l10n/bundle.l10n.ru.json
  l10n/bundle.l10n.zh-CN.json
  media/tutorials/flash_encryption/flash-encryption.png
  media/tutorials/flash_encryption/flash-encryption2.png
  src/config.ts
  src/efuse/index.ts
  src/efuse/view/item_generator.ts
  src/espIdf/documentation/getDocsVersion.ts
  src/extension.ts
  src/flash/verifyFlashEncryption.ts
  src/logger/utils.ts
  src/utils.ts
Labels: enhancement, ongoing

#1298 [VSC-1258] feature/walkthrough
  .vscode/settings.json
  media/walkthrough/commands-section.png
  media/walkthrough/create-project.png
  media/walkthrough/esp-idf-explorer.png
  media/walkthrough/examples-list.png
  media/walkthrough/express-setup.png
  media/walkthrough/gifs/configure-jtag-h2.gif
  media/walkthrough/gifs/create-example-from-component.gif
  media/walkthrough/gifs/debug.gif
  media/walkthrough/gifs/install-component.gif
  media/walkthrough/gifs/menuconfig.gif
  media/walkthrough/gifs/partition-table.gif
  media/walkthrough/gifs/size-analysis-gui.gif
  media/walkthrough/gifs/unit-testing.gif
  media/walkthrough/hints-viewer.png
  media/walkthrough/icons/build-flash-monitor.png
  media/walkthrough/icons/build.png
  media/walkthrough/icons/debug.png
  media/walkthrough/icons/device-target.png
  media/walkthrough/icons/flash-method.png
  media/walkthrough/icons/flash.png
  media/walkthrough/icons/monitor.png
  media/walkthrough/icons/port.png
  media/walkthrough/icons/run-and-debug.png
  media/walkthrough/icons/sdkconfig.png
  media/walkthrough/idf-version.png
  media/walkthrough/install-btn.png
  media/walkthrough/peripheral-viewer.png
  media/walkthrough/project-components.png
  media/walkthrough/python-selection.png
  media/walkthrough/size-analysis.png
  media/walkthrough/status-bar.png
  package.json
  package.nls.es.json
  package.nls.json
  package.nls.pt.json
  package.nls.ru.json
  package.nls.zh-CN.json
  src/checkExtensionSettings.ts
  src/extension.ts
  walkthroughs/advanced/advanced-conclusion.md
  walkthroughs/advanced/advanced-intro.md
  walkthroughs/advanced/app-size-analysis.md
  walkthroughs/advanced/component-installation.md
  walkthroughs/advanced/debug-project.md
  walkthroughs/advanced/multi-project.md
  walkthroughs/advanced/partition-table.md
  walkthroughs/advanced/sdk-configuration.md
  walkthroughs/advanced/troubleshooting.md
  walkthroughs/advanced/unit-testing.md
  walkthroughs/basic/additional-resources.md
  walkthroughs/basic/basic-usage-intro.md
  walkthroughs/basic/build-flash-monitor.md
  walkthroughs/basic/configuration.md
  walkthroughs/basic/create-project.md
  walkthroughs/basic/setup-project.md
Labels: ongoing

#1341 docs: Provide CN translation for settings.rst
  docs_espressif/en/index.rst
  docs_espressif/en/settings.rst
  docs_espressif/zh_CN/additionalfeatures.rst
  docs_espressif/zh_CN/additionalfeatures/app-tracing.rst
  docs_espressif/zh_CN/additionalfeatures/application-size-analysis.rst
  docs_espressif/zh_CN/additionalfeatures/cmakelists-editor.rst
  docs_espressif/zh_CN/additionalfeatures/coverage.rst
  docs_espressif/zh_CN/additionalfeatures/dfu.rst
  docs_espressif/zh_CN/additionalfeatures/docker-container.rst
  docs_espressif/zh_CN/additionalfeatures/efuse.rst
  docs_espressif/zh_CN/additionalfeatures/esp-terminal.rst
  docs_espressif/zh_CN/additionalfeatures/flash-encryption.rst
  docs_espressif/zh_CN/additionalfeatures/heap-tracing.rst
  docs_espressif/zh_CN/additionalfeatures/hints-viewer.rst
  docs_espressif/zh_CN/additionalfeatures/install-esp-components.rst
  docs_espressif/zh_CN/additionalfeatures/multiple-projects.rst
  docs_espressif/zh_CN/additionalfeatures/nvs-partition-editor.rst
  docs_espressif/zh_CN/additionalfeatures/partition-table-editor.rst
  docs_espressif/zh_CN/additionalfeatures/project-configuration.rst
  docs_espressif/zh_CN/additionalfeatures/qemu.rst
  docs_espressif/zh_CN/additionalfeatures/rainmaker.rst
  docs_espressif/zh_CN/additionalfeatures/unit-testing.rst
  docs_espressif/zh_CN/additionalfeatures/wsl.rst
  docs_espressif/zh_CN/buildproject.rst
  docs_espressif/zh_CN/commands.rst
  docs_espressif/zh_CN/configureproject.rst
  docs_espressif/zh_CN/connectdevice.rst
  docs_espressif/zh_CN/debugproject.rst
  docs_espressif/zh_CN/faqs.rst
  docs_espressif/zh_CN/flashdevice.rst
  docs_espressif/zh_CN/index.rst
  docs_espressif/zh_CN/installation.rst
  docs_espressif/zh_CN/monitoroutput.rst
  docs_espressif/zh_CN/prerequisites.rst
  docs_espressif/zh_CN/settings.rst
  docs_espressif/zh_CN/startproject.rst
  docs_espressif/zh_CN/troubleshooting.rst
Labels: documentation 📝
