Repository espressif/vscode-esp-idf-extension, pull requests merged in 2025-03, with the labels that each got.

#1426 [VSC-1434] add prefix_map_gdbinit initCommands if reproducible build
  src/cdtDebugAdapter/debugConfProvider.ts
Labels: bugfix

#1454 docs: Provide CN translation for 3 index docs
  docs_espressif/en/additionalfeatures/coverage.rst
  docs_espressif/en/faqs.rst
  docs_espressif/en/installation.rst
  docs_espressif/en/startproject.rst
  docs_espressif/en/troubleshooting.rst
  docs_espressif/zh_CN/installation.rst
  docs_espressif/zh_CN/startproject.rst
  docs_espressif/zh_CN/troubleshooting.rst
Labels: documentation 📝

#1441 [VSC-1597] preBuild wrongly used in project conf idf.preFlashTask
  src/idfConfiguration.ts
Labels: bugfix

#1429 [VSC-1496] add idf monitorPort conf setting and cmds
  docs_espressif/en/settings.rst
  l10n/bundle.l10n.es.json
  l10n/bundle.l10n.pt.json
  l10n/bundle.l10n.ru.json
  l10n/bundle.l10n.zh-CN.json
  package.json
  package.nls.es.json
  package.nls.json
  package.nls.pt.json
  package.nls.ru.json
  package.nls.zh-CN.json
  src/cmdTreeView/cmdStore.ts
  src/espIdf/monitor/command.ts
  src/espIdf/serial/serialPort.ts
  src/extension.ts
  src/statusBar/index.ts
Labels: enhancement

#1453 [VSC-1563] add debug conf web extension doc
  docs/DEBUGGING.md
  docs_espressif/en/additionalfeatures.rst
  docs_espressif/en/additionalfeatures/web-extension.rst
  docs_espressif/en/debugproject.rst
  docs_espressif/zh_CN/additionalfeatures.rst
  docs_espressif/zh_CN/additionalfeatures/web-extension.rst
Labels: needs translation:CN, documentation 📝

#1462 [VSC-1604 | VSC-1606 | VSC-1624] use idf py qemu Allow qemu debug monitor
  docs_espressif/en/additionalfeatures/qemu.rst
  docs_espressif/en/settings.rst
  docs_espressif/zh_CN/settings.rst
  package.json
  package.nls.es.json
  package.nls.json
  package.nls.pt.json
  package.nls.ru.json
  package.nls.zh-CN.json
  src/build/buildCmd.ts
  src/extension.ts
  src/qemu/mergeFlashBin.ts
  src/qemu/qemuManager.ts
Labels: enhancement

#1472 docs: Provide CN translation for wsl.rst
  docs_espressif/en/additionalfeatures/wsl.rst
  docs_espressif/zh_CN/additionalfeatures/wsl.rst
Labels: documentation 📝
